import { Lot } from './types';

export const LOTS: Lot[] = [
  {
    id: 1,
    property_number: 1,
    parcel_id: "04-5A-1-196",
    county: "Monroe",
    city: "Tobyhanna",
    state: "PA",
    amv: 14500,
    lot_size_acres: 0.46,
    display_address: "Lot 196, Pocono Farms East",
    surrounding_facilities: "Lake access · Clubhouse · Private community",
    image_grad: "linear-gradient(135deg, #1a3a2e 0%, #0d2a20 50%, #06131b 100%)",
    tag: "WOODED",
    images: [
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-1-196/photo-1.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-1-196/photo2.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-1-196/photo3.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-1-196/photo4.jpg",
    ],
  },
  {
    id: 2,
    property_number: 2,
    parcel_id: "09-7B-2-182",
    county: "Pike",
    city: "Dingmans Ferry",
    state: "PA",
    amv: 18900,
    lot_size_acres: 1.12,
    display_address: "Lot 182, Sunrise Lake Estates",
    surrounding_facilities: "Lakefront · Fishing · Hiking trails",
    image_grad: "linear-gradient(135deg, #0f2a3a 0%, #0a1e2d 50%, #050d18 100%)",
    tag: "LAKEFRONT",
    images: [
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-2-182/cover.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-2-182/photo1.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-2-182/photo2.jpg",
    ],
  },
  {
    id: 4,
    property_number: 4,
    parcel_id: "12-3C-4-189",
    county: "Wayne",
    city: "Lake Ariel",
    state: "PA",
    amv: 22400,
    lot_size_acres: 1.38,
    display_address: "Lot 189, Hideout Community",
    surrounding_facilities: "Ski resort · Golf · Beach club",
    image_grad: "linear-gradient(135deg, #2e1f3a 0%, #1e1529 50%, #0d091a 100%)",
    tag: "RESORT",
    images: [
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-4-189/photo-2.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-4-189/photo3.jpg",
    ],
  },
  {
    id: 5,
    property_number: 5,
    parcel_id: "08-2D-5-188",
    county: "Monroe",
    city: "Pocono Lake",
    state: "PA",
    amv: 12750,
    lot_size_acres: 0.52,
    display_address: "Lot 188, Arrowhead Lake",
    surrounding_facilities: "Private lake · Beaches · Pool",
    image_grad: "linear-gradient(135deg, #1a2e3a 0%, #0f1e28 50%, #060f18 100%)",
    tag: "BUILDABLE",
    images: [
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-5-188/cover.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-5-188/photo1.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-5-188/photo2.jpg",
    ],
  },
  {
    id: 6,
    property_number: 6,
    parcel_id: "15-6A-6-187",
    county: "Lackawanna",
    city: "Moscow",
    state: "PA",
    amv: 16200,
    lot_size_acres: 0.89,
    display_address: "Lot 187, Sterling Pine",
    surrounding_facilities: "Forest · Stream · Quiet road",
    image_grad: "linear-gradient(135deg, #1a3a35 0%, #0f2825 50%, #061816 100%)",
    tag: "SECLUDED",
    images: [
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-6-187/cover.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-6-187/photo1.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-6-187/photo2.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-6-187/photo3.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-6-187/photo4.jpg",
    ],
  },
  {
    id: 7,
    property_number: 7,
    parcel_id: "11-4E-7-191",
    county: "Carbon",
    city: "Weatherly",
    state: "PA",
    amv: 9800,
    lot_size_acres: 0.35,
    display_address: "Lot 191, Ridge View",
    surrounding_facilities: "Mountain views · Hiking · Quiet",
    image_grad: "linear-gradient(135deg, #1a2e3a 0%, #0d1f2d 50%, #050d18 100%)",
    tag: "AFFORDABLE",
    images: [
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-7-191/cover.jpg",
    ],
  },
  {
    id: 8,
    property_number: 8,
    parcel_id: "13-5F-8-185",
    county: "Pike",
    city: "Hawley",
    state: "PA",
    amv: 21500,
    lot_size_acres: 1.55,
    display_address: "Lot 185, Eagle Ridge",
    surrounding_facilities: "Water access · Trails · Community",
    image_grad: "linear-gradient(135deg, #0f2a3a 0%, #081d2d 50%, #030a15 100%)",
    tag: "PREMIUM",
    images: [
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-8-185/cover.jpg",
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-8-185/photo1.jpg",
    ],
  },
  {
    id: 9,
    property_number: 9,
    parcel_id: "14-6G-9-190",
    county: "Wayne",
    city: "Lakewood",
    state: "PA",
    amv: 19200,
    lot_size_acres: 0.98,
    display_address: "Lot 190, Lakewood Estates",
    surrounding_facilities: "Community amenities · Access road",
    image_grad: "linear-gradient(135deg, #2e1f3a 0%, #1d1228 50%, #0a0510 100%)",
    tag: "COMMUNITY",
    images: [
      "https://yeyjuavggvcalbsgorkr.supabase.co/storage/v1/object/public/property-images/lot-9-190/cover.jpg",
    ],
  },
];
